# Generated by Django 5.2.13 on 2026-07-22 12:22

import uuid
from django.db import migrations, models


def clear_pins_and_boards(apps, schema_editor):
    """Old ``unique_id`` values are random numeric strings that cannot be cast
    to UUIDs, so the varchar->uuid column change would fail on existing rows.
    These IDs are disposable (all pin/board data is seeded), so we clear the
    tables first; re-run seeding after migrating. Deleting boards and pins
    cascades to their ``PinInBoard`` join rows."""
    Board = apps.get_model("pinit_api", "Board")
    Pin = apps.get_model("pinit_api", "Pin")
    Board.objects.all().delete()
    Pin.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_api', '0031_rename_title_board_name_board_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_pins_and_boards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='board',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
