FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

WORKDIR /app

COPY . /app

RUN DJANGO_SECRET_KEY=build \
    POSTGRES_HOST=localhost \
    POSTGRES_DB=build \
    POSTGRES_USER=build \
    POSTGRES_PASSWORD=build \
    python manage.py collectstatic --noinput

EXPOSE 80

ENV DJANGO_SETTINGS_MODULE=pinit.settings.aws_staging

CMD ["gunicorn", "--workers=3", "--bind=0.0.0.0:80", "pinit.wsgi:application"]
