apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinit-staging

resources:
- ../../base/backend
- namespace.yaml
- externalsecret.yaml

images:
- name: pinit-api
  newName: 771527521576.dkr.ecr.eu-west-3.amazonaws.com/pinit-api
  newTag: 99adbac515483dab4c00ae3308fc0e709c570872
