apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinit-staging

resources:
  - ../../base/backend
  - namespace.yaml
  - externalsecret.yaml

images:
  - name: pinit-api
    newName: ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/pinit-api
    newTag: latest
