name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Detect changed paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/check-pull-request.yml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/check-pull-request.yml'
            e2e:
              - 'e2e-tests-web/**'
              - '.github/workflows/check-pull-request.yml'

  backend-checks:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    environment:
      name: test
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker container
        run: docker compose -f docker-compose.test.yml up -d

      - name: Run migrations
        run: docker compose -f docker-compose.test.yml exec -T web python manage.py migrate

      - name: Run tests
        run: docker compose -f docker-compose.test.yml exec -T web python manage.py test

      - name: Shut down Docker container
        run: docker compose -f docker-compose.test.yml down

  frontend-checks:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Type-check
        run: pnpm type-check

      - name: Run component tests
        run: pnpm jest

  e2e-checks:
    needs: detect-changes
    if: needs.detect-changes.outputs.e2e == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-tests-web
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      - name: Install dependencies
        run: pnpm install

      - name: Type-check
        run: pnpm type-check

      # NB: we don't actually run the E2E tests in the CI for now.
